# Generated by Django 4.0.10 on 2024-07-12 17:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_rename_article_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Article',
        ),
    ]
