# Generated by Django 5.0.6 on 2024-08-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_remove_image_uploaded_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
